const mongoose = require("mongoose");
const Schema = mongoose.Schema;
const passportLocalMongoose = require("passport-local-mongoose")

const userSchema = new Schema({
  email: {
    type: String,
    require: true
  },
  // username and password is automatically generated by passportLocalMongoose along with salting and hashing //
});

userSchema.plugin(passportLocalMongoose);

module.exports = mongoose.model('User', userSchema);